//! GUI D-Bus client: `DaemonClient` proxy + `SignalCoalescer` + bus resolution.
//!
//! The GUI never touches SQLite — all data flows through the daemon's D-Bus API
//! (`org.wellbeing.v1.Daemon`). Responses are cached via `ClientCache` with
//! stale-while-revalidate semantics.
//!
//! ## Architecture (06-daemon-dbus.md / 09-state-flow.md)
//!
//! - `DaemonClient` wraps a zbus proxy and per-method `ClientCache` instances.
//! - `SignalCoalescer` converts bursty D-Bus signals into coalesced notifications.
//! - `resolve_daemon_bus()` implements the 4-step resolution from 13-deployment-modes.md.

use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::Duration;

use anyhow::{Context, Result};
use futures::StreamExt;
use tokio::sync::mpsc;
use tracing::{info, warn};
use wellbeing_core::dbus_constants::DAEMON_BUS_NAME;
use wellbeing_core::*;
use zbus::Connection;
use zbus::proxy;

use crate::cache::ClientCache;

// ── D-Bus proxy trait (generated by zbus compile-time macro) ────────────────

#[proxy(
    interface = "org.wellbeing.v1.Controller",
    default_service = "org.wellbeing.v1.Controller",
    default_path = "/org/wellbeing/Controller"
)]
trait Daemon {
    /// ═══ Policy CRUD ═══
    async fn list_policies(&self, filter_owner: u32) -> zbus::Result<Vec<Policy>>;
    async fn create_policy(&self, input: PolicyInput) -> zbus::Result<PolicyId>;
    async fn update_policy(&self, id: PolicyId, input: PolicyInput) -> zbus::Result<()>;
    async fn delete_policy(&self, id: PolicyId) -> zbus::Result<()>;

    /// ═══ Usage Data ═══
    async fn get_daily_usage(&self, date: &str, user_id: u32)
    -> zbus::Result<Vec<DailyUsageEntry>>;
    async fn get_usage_range(
        &self,
        start_date: &str,
        end_date: &str,
        user_id: u32,
    ) -> zbus::Result<Vec<DailySummary>>;

    /// ═══ Categories ═══
    async fn list_categories(&self) -> zbus::Result<Vec<Category>>;
    async fn get_app_categories(&self) -> zbus::Result<Vec<AppCategoryRow>>;
    async fn set_app_category(&self, app_id: &str, category_id: CategoryId) -> zbus::Result<()>;

    /// ═══ Block State ═══
    #[zbus(property)]
    fn active_blocks(&self) -> zbus::Result<Vec<ActiveBlockEntry>>;

    /// ═══ Signals (non-async — zbus generates receivers) ═══
    #[zbus(signal)]
    fn block_state_changed(&self) -> zbus::Result<(u32, String, bool, u32)>;

    #[zbus(signal)]
    fn daily_usage_changed(&self) -> zbus::Result<u32>;

    #[zbus(signal)]
    fn policy_mutated(&self) -> zbus::Result<u32>;
}

// ── Signal Coalescer ────────────────────────────────────────────────────────

/// Coalesces rapid-fire D-Bus signals into periodic cache invalidations.
#[derive(Debug)]
pub struct SignalCoalescer {
    blocked_dirty: Arc<AtomicBool>,
    usage_dirty: Arc<AtomicBool>,
    policy_dirty: Arc<AtomicBool>,
}

/// Bitmask of dirty flags returned by `SignalCoalescer::drain()`.
#[derive(Debug, Clone, Copy, Default)]
pub struct CoalescedNotifications {
    pub blocked: bool,
    pub usage: bool,
    pub policy: bool,
}

impl CoalescedNotifications {
    pub fn any(&self) -> bool {
        self.blocked || self.usage || self.policy
    }
}

impl SignalCoalescer {
    pub fn new() -> Self {
        Self {
            blocked_dirty: Arc::new(AtomicBool::new(false)),
            usage_dirty: Arc::new(AtomicBool::new(false)),
            policy_dirty: Arc::new(AtomicBool::new(false)),
        }
    }

    pub fn mark_blocked_dirty(&self) {
        self.blocked_dirty.store(true, Ordering::Release);
    }

    pub fn mark_daily_usage_dirty(&self) {
        self.usage_dirty.store(true, Ordering::Release);
    }

    pub fn mark_policy_dirty(&self) {
        self.policy_dirty.store(true, Ordering::Release);
    }

    pub fn drain(&self) -> CoalescedNotifications {
        CoalescedNotifications {
            blocked: self.blocked_dirty.swap(false, Ordering::AcqRel),
            usage: self.usage_dirty.swap(false, Ordering::AcqRel),
            policy: self.policy_dirty.swap(false, Ordering::AcqRel),
        }
    }
}

impl Default for SignalCoalescer {
    fn default() -> Self {
        Self::new()
    }
}

// ── DaemonClient ────────────────────────────────────────────────────────────

/// Thin wrapper around the daemon's `org.wellbeing.v1.Daemon` D-Bus API.
#[derive(Debug, Clone)]
pub struct DaemonClient {
    proxy: DaemonProxy<'static>,
    conn: Connection,
    range_cache: Arc<ClientCache<String, Vec<DailySummary>>>,
    policy_cache: Arc<ClientCache<String, Vec<Policy>>>,
    category_cache: Arc<ClientCache<String, Vec<Category>>>,
    app_category_cache: Arc<ClientCache<String, Vec<AppCategoryRow>>>,
}

impl DaemonClient {
    /// Connect to the daemon using the 4-step bus resolution.
    pub async fn connect() -> Result<Self> {
        let conn = resolve_daemon_bus()
            .await
            .context("wellbeing daemon unreachable (all 4 bus resolution steps failed)")?;

        let proxy = DaemonProxy::new(&conn)
            .await
            .context("failed to create daemon D-Bus proxy")?;

        Ok(Self {
            proxy,
            conn,
            range_cache: Arc::new(ClientCache::new(Duration::from_millis(500))),
            policy_cache: Arc::new(ClientCache::new(Duration::from_secs(5))),
            category_cache: Arc::new(ClientCache::new(Duration::from_secs(5))),
            app_category_cache: Arc::new(ClientCache::new(Duration::from_secs(5))),
        })
    }

    /// Create a degraded client from a raw connection (daemon may not be available).
    pub async fn degraded(conn: Connection) -> Self {
        let proxy = DaemonProxy::new(&conn)
            .await
            .expect("failed to create degraded daemon proxy");
        Self {
            proxy,
            conn,
            range_cache: Arc::new(ClientCache::new(Duration::from_millis(500))),
            policy_cache: Arc::new(ClientCache::new(Duration::from_secs(5))),
            category_cache: Arc::new(ClientCache::new(Duration::from_secs(5))),
            app_category_cache: Arc::new(ClientCache::new(Duration::from_secs(5))),
        }
    }

    /// The underlying zbus connection (for signal subscriptions).
    pub fn connection(&self) -> &Connection {
        &self.conn
    }

    // ── Policy CRUD ──

    pub async fn list_policies(&self, filter_owner: u32) -> Result<Vec<Policy>> {
        let key = format!("policies:{}", filter_owner);
        if let Some(cached) = self.policy_cache.get(&key) {
            return Ok(cached);
        }
        let policies = self.proxy.list_policies(filter_owner).await?;
        self.policy_cache.set(key, policies.clone());
        Ok(policies)
    }

    pub async fn create_policy(&self, input: PolicyInput) -> Result<PolicyId> {
        let id = self.proxy.create_policy(input).await?;
        self.policy_cache.clear();
        Ok(id)
    }

    pub async fn update_policy(&self, id: PolicyId, input: PolicyInput) -> Result<()> {
        self.proxy.update_policy(id, input).await?;
        self.policy_cache.clear();
        Ok(())
    }

    pub async fn delete_policy(&self, id: PolicyId) -> Result<()> {
        self.proxy.delete_policy(id).await?;
        self.policy_cache.clear();
        Ok(())
    }

    // ── Usage Data ──

    pub async fn get_usage_range(
        &self,
        start_date: &str,
        end_date: &str,
        user_id: u32,
    ) -> Result<Vec<DailySummary>> {
        let key = format!("range:{}:{}:{}", start_date, end_date, user_id);
        if let Some(cached) = self.range_cache.get(&key) {
            return Ok(cached);
        }
        let summaries = self
            .proxy
            .get_usage_range(start_date, end_date, user_id)
            .await?;
        self.range_cache.set(key, summaries.clone());
        Ok(summaries)
    }

    // ── Categories ──

    pub async fn list_categories(&self) -> Result<Vec<Category>> {
        let key = "categories".into();
        if let Some(cached) = self.category_cache.get(&key) {
            return Ok(cached);
        }
        let cats = self.proxy.list_categories().await?;
        self.category_cache.set(key, cats.clone());
        Ok(cats)
    }

    pub async fn get_app_categories(&self) -> Result<Vec<AppCategoryRow>> {
        let key = "app_categories".into();
        if let Some(cached) = self.app_category_cache.get(&key) {
            return Ok(cached);
        }
        let rows = self.proxy.get_app_categories().await?;
        self.app_category_cache.set(key, rows.clone());
        Ok(rows)
    }

    pub async fn set_app_category(&self, app_id: &str, category_id: CategoryId) -> Result<()> {
        self.proxy.set_app_category(app_id, category_id).await?;
        self.app_category_cache.clear();
        self.category_cache.clear();
        Ok(())
    }

    // ── Cache Invalidation ──

    pub fn invalidate_range_cache(&self) {
        self.range_cache.clear();
    }
    pub fn invalidate_policy_cache(&self) {
        self.policy_cache.clear();
    }
    pub fn invalidate_category_caches(&self) {
        self.category_cache.clear();
        self.app_category_cache.clear();
    }
}

// ── Bus Resolution (4-step algorithm from 13-deployment-modes.md) ──────────

/// Resolve which bus hosts `org.wellbeing.v1.Controller`.
async fn resolve_daemon_bus() -> Option<Connection> {
    let sys = Connection::system().await.ok();
    let sess = Connection::session().await.ok();

    if let Some(ref c) = sys
        && name_owner_present(c, DAEMON_BUS_NAME).await
    {
        info!("daemon found on system bus");
        return Some(c.clone());
    }
    if let Some(ref c) = sess
        && name_owner_present(c, DAEMON_BUS_NAME).await
    {
        info!("daemon found on session bus");
        return Some(c.clone());
    }
    if let Some(ref c) = sys
        && start_service_by_name(c, DAEMON_BUS_NAME).await
        && name_owner_present(c, DAEMON_BUS_NAME).await
    {
        info!("daemon activated on system bus");
        return Some(c.clone());
    }
    if let Some(ref c) = sess
        && start_service_by_name(c, DAEMON_BUS_NAME).await
        && name_owner_present(c, DAEMON_BUS_NAME).await
    {
        info!("daemon activated on session bus");
        return Some(c.clone());
    }
    warn!("daemon unreachable (degraded mode)");
    None
}

async fn name_owner_present(conn: &Connection, name: &str) -> bool {
    use zbus::fdo::DBusProxy;
    use zbus::names::BusName;
    match DBusProxy::new(conn).await {
        Ok(proxy) => {
            let Ok(bus_name) = BusName::try_from(name) else {
                return false;
            };
            proxy.name_has_owner(bus_name).await.unwrap_or(false)
        }
        Err(_) => false,
    }
}

async fn start_service_by_name(conn: &Connection, name: &str) -> bool {
    use zbus::fdo::DBusProxy;
    use zbus::names::WellKnownName;
    match DBusProxy::new(conn).await {
        Ok(proxy) => {
            let Ok(well_known) = WellKnownName::try_from(name) else {
                return false;
            };
            match proxy.start_service_by_name(well_known, 0u32).await {
                Ok(r) => r == 1 || r == 2,
                Err(_) => false,
            }
        }
        Err(_) => false,
    }
}

// ── Signal Subscription ─────────────────────────────────────────────────────

/// Subscribe to daemon signals and forward coalesced notifications to the GPUI thread.
pub fn spawn_signal_listener(
    client: &DaemonClient,
    coalescer: Arc<SignalCoalescer>,
    signal_tx: mpsc::UnboundedSender<CoalescedNotifications>,
) {
    let conn = client.connection().clone();
    tokio::spawn(async move {
        let proxy = match DaemonProxy::new(&conn).await {
            Ok(p) => p,
            Err(e) => {
                warn!(%e, "failed signal proxy");
                return;
            }
        };

        let tx = signal_tx.clone();
        let coal = coalescer.clone();
        if let Ok(mut stream) = proxy.receive_block_state_changed().await {
            tokio::spawn(async move {
                while let Some(msg) = stream.next().await {
                    if msg
                        .message()
                        .body()
                        .deserialize::<(u32, String, bool, u32)>()
                        .is_ok()
                    {
                        coal.mark_blocked_dirty();
                        let _ = tx.send(CoalescedNotifications {
                            blocked: true,
                            ..Default::default()
                        });
                    }
                }
            });
        }

        let tx = signal_tx.clone();
        let coal = coalescer.clone();
        if let Ok(mut stream) = proxy.receive_daily_usage_changed().await {
            tokio::spawn(async move {
                while let Some(msg) = stream.next().await {
                    if msg.message().body().deserialize::<u32>().is_ok() {
                        coal.mark_daily_usage_dirty();
                        let _ = tx.send(CoalescedNotifications {
                            usage: true,
                            ..Default::default()
                        });
                    }
                }
            });
        }

        let coal = coalescer.clone();
        if let Ok(mut stream) = proxy.receive_policy_mutated().await {
            tokio::spawn(async move {
                while let Some(msg) = stream.next().await {
                    if msg.message().body().deserialize::<u32>().is_ok() {
                        coal.mark_policy_dirty();
                        let _ = signal_tx.send(CoalescedNotifications {
                            policy: true,
                            ..Default::default()
                        });
                    }
                }
            });
        }
    });
}
